import React from 'react';

export const metadata = {
    title: 'Create Login App',
    description: 'Generated by create next app',
}

function Page(props) {
    return (
        <div>hello5</div>
    );
}

export default Page;